//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "container_runtime_stats")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub collected_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::container_stats::Entity")]
    ContainerStats,
}

impl Related<super::container_stats::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ContainerStats.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
