//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "container_stats")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub container_runtime_stats_id: i64,
    pub container_runtime: String,
    pub container_id: String,
    pub host_name: String,
    pub created_at: i64,
    pub status: String,
    pub running: bool,
    pub running_for_seconds: i64,
    pub image_name: String,
    pub networks: String,
    #[sea_orm(column_type = "Double")]
    pub cpu_usage_percent: f64,
    pub memory_usage_bytes: i64,
    pub collected_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::container_runtime_stats::Entity",
        from = "Column::ContainerRuntimeStatsId",
        to = "super::container_runtime_stats::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    ContainerRuntimeStats,
}

impl Related<super::container_runtime_stats::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ContainerRuntimeStats.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
