//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "cpu_core_stats")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub cpu_stats_id: i64,
    pub core_name: String,
    #[sea_orm(column_type = "Float")]
    pub core_usage_percent: f32,
    pub core_frequency_mhz: i64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::cpu_stats::Entity",
        from = "Column::CpuStatsId",
        to = "super::cpu_stats::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    CpuStats,
}

impl Related<super::cpu_stats::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CpuStats.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
