//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "cpu_stats")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub cpu_name: String,
    pub cpu_count: i64,
    pub cpu_physical_count: i64,
    #[sea_orm(column_type = "Float")]
    pub cpu_usage_percent: f32,
    #[sea_orm(column_type = "Float")]
    pub cpu_temperature_celsius: f32,
    pub collected_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::cpu_core_stats::Entity")]
    CpuCoreStats,
}

impl Related<super::cpu_core_stats::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CpuCoreStats.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
