//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "disk_entry")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub collected_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::disk_stats::Entity")]
    DiskStats,
}

impl Related<super::disk_stats::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::DiskStats.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
