//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "error")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub file: Option<String>,
    pub line: i64,
    pub severity: Option<String>,
    pub message: Option<String>,
    pub collected_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
