//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "memory_stats")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub total_memory_in_byte: i64,
    pub available_memory_in_byte: i64,
    pub used_memory_in_byte: i64,
    pub total_swap_in_byte: i64,
    pub available_swap_in_byte: i64,
    pub used_swap_in_byte: i64,
    pub collected_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
