//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "network_stats")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub local_ip: String,
    pub total_bytes_transmitted: i64,
    pub total_bytes_received: i64,
    pub total_packets_transmitted: i64,
    pub total_packets_received: i64,
    pub collected_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
