//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "partition_stats")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub partition_entry_id: i64,
    pub name: String,
    pub device: String,
    pub mount_point: String,
    pub fs_type: String,
    pub total_bytes: i64,
    pub used_bytes: i64,
    pub available_bytes: i64,
    pub used_blocks: i64,
    pub available_blocks: i64,
    pub block_size: i64,
    pub collected_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::partition_entry::Entity",
        from = "Column::PartitionEntryId",
        to = "super::partition_entry::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    PartitionEntry,
}

impl Related<super::partition_entry::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PartitionEntry.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
