//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

pub use super::container_runtime_stats::Entity as ContainerRuntimeStats;
pub use super::container_stats::Entity as ContainerStats;
pub use super::cpu_core_stats::Entity as CpuCoreStats;
pub use super::cpu_stats::Entity as CpuStats;
pub use super::disk_stats::Entity as DiskStats;
pub use super::memory_stats::Entity as MemoryStats;
pub use super::network_stats::Entity as NetworkStats;
pub use super::process_stats::Entity as ProcessStats;
pub use super::processes_stats::Entity as ProcessesStats;
pub use super::speedtest_stats::Entity as SpeedtestStats;
pub use super::system_stats::Entity as SystemStats;
