//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "process_stats")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub processes_stats_id: i64,
    pub kind: String,
    pub pid: i64,
    pub name: String,
    pub user_name: String,
    pub status: String,
    #[sea_orm(column_type = "Float")]
    pub cpu_usage_percent: f32,
    pub memory_usage_bytes: i64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::processes_stats::Entity",
        from = "Column::ProcessesStatsId",
        to = "super::processes_stats::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    ProcessesStats,
}

impl Related<super::processes_stats::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ProcessesStats.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
