//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "system_stats")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub os_name: Option<String>,
    pub uptime_seconds: i64,
    pub host_name: Option<String>,
    pub kernel_version: String,
    pub collected_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
